import { z } from "zod";

export const OMStatus = z.enum([
  "DRAFT",
  "BROKER_APPROVED",
  "SELLER_APPROVED",
  "MARKETING"
]);

export const OMSectionDefinition = z.object({
  id: z.string(),
  title: z.string(),
  required: z.boolean(),
  fields: z.array(z.string()),
  autogenerated: z.boolean().optional()
});

export const OMSectionsResponse = z.object({
  sections: z.array(OMSectionDefinition),
  statuses: z.record(z.string())
});

export const OMGenerateRequest = z.object({
  regenerate: z.boolean().optional()
});

export const OMUpdateSectionRequest = z.object({
  content: z.unknown()
});

export const OMRequestChangesRequest = z.object({
  feedback: z.string()
});

export const OMApproval = z.object({
  brokerApprovedBy: z.string().nullable().optional(),
  brokerApprovedAt: z.string().nullable().optional(),
  sellerApprovedBy: z.string().nullable().optional(),
  sellerApprovedAt: z.string().nullable().optional()
});

export const OMVersion = z.object({
  id: z.string(),
  dealDraftId: z.string(),
  versionNumber: z.number(),
  status: OMStatus,
  approval: OMApproval,
  createdBy: z.string(),
  createdByName: z.string(),
  createdAt: z.string(),
  content: z.unknown().optional(),
  claimRefs: z.array(z.string()).optional(),
  changeLog: z.array(z.string()).optional()
});

export const OMVersionListResponse = z.object({
  versions: z.array(OMVersion)
});
